import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {fetchSingleType} from "@/lib/strapi/client";
import {Suspense} from "react";
import {Header} from "@/components/layout/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const query = {
    populate: {
      header: {
        fields: [],
        populate: {
          logo: {
            fields: ['logoText'],
            populate: {
              image: {
                fields: ["url", "alternativeText"],
              },
            },
          },
          dropdown: {
            fields: ['title'],
            populate : {
              sections: {
                fields: ['heading'],
                populate: {
                  links: true,
                }
              }
            }
          },
          link: true,
          cta: true,
        },
      },
    },
  }

  const {header} = await fetchSingleType('sample-header', query)

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200`}>

      <Suspense fallback={null}>
        <Header data={header} />
      </Suspense>

        {children}
      </body>
    </html>
  );
}


