import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {fetchSingleType} from "@/lib/strapi/client";
import {Header} from "@/components/layout/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// async function loader() {
//   const { data } = await getGlobalSettings()
//   if (!data) throw new Error("Sorry, failed to fetch global settings.");
//   return { header: data?.header};
// }

const globalSettingQuery = {
  populate: {
    header: {
      populate: {
        logo: {
          populate: {
            image: {
              fields: ["url", "alternativeText"],
            },
          },
        },
        navigation: true,
        cta: true,
      },
    },
  },
}


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const {header} = await loader();
  const {header} = await fetchSingleType('tf-global', globalSettingQuery)
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200`}>
      <Header data={header} />
        {children}
      </body>
    </html>
  );
}


